### PR TITLE
example of sha256 in assembly script

### PR DESCRIPTION
**Pull request by mpetrunic**
Basically my idea that can work is to create plain object
```javascript
export interface Sha256 {
  m_h: u32[];
  m_block: int32[];//TODO: or something more appropriate for char array
  m_len: i32;
  m_tot_len: i32;
}
```
in init method, return it and pass it to update/transform/final methods.
You could create in js/ts wrapper class to make it easier to use.

I wouldn't merge this as I figured to late that there was some invalid c++ to assembly scripot conversion like:
`memcpy(mBlock + m_len, message, rem_len);`
should be something like
`Sha256.m_block.fill(message, Sha256.m_len, Sha256.m_len + rem_len)`

I will focus on rust->wasm for sha256 as I'm unable to compile this
`Import file '~lib/allocator/arena.ts' not found.`

### CODE REVIEW

**Comment by mpetrunic** [comment]
@gregthegreek 😊

**Comment by GregTheGreek** [comment]
Wow! Great work, yeah I want sure about memcpy but I'll take this and finish it off :)

**Comment by GregTheGreek** [comment]
@tueric assigning to you

**Comment by tueric** [comment]
I believe that AS has a memcpy function in the allocator. See here: https://github.com/AssemblyScript/assemblyscript/blob/0484a6b740b996145f10ad227359be614c190208/std/assembly/util/memory.ts#L1

**Comment by tueric** [comment]
As an update for @mpetrunic, I have ported two other implementations of SHA256 to AS before, namely these two implementations: https://github.com/dchest/fast-sha256-js AND https://github.com/emn178/js-sha256. 

Sadly, I don't get correct outputs. HOWEVER, the weird thing is, they're both wrong in the same way, which is weird.

**Comment by mpetrunic** [comment]
@tueric I'm not AS expert though. This c++ implementation seems pretty straightforward, so we might be able to find cause if it doesn't work in AS.

**Comment by GregTheGreek** [comment]
> Sadly, I don't get correct outputs. HOWEVER, the weird thing is, they're both wrong in the same way, which is weird.

They produce the same incorrect output?

**Comment by tueric** [comment]
@GregTheGreek Yes.

**Pull request closed without merging**
