### PR TITLE
Disclude wasm/wast blobs from npm package

### PR DESCRIPTION
**Pull request by wemeetagain**
Drops unpacked package size from 87.5kb to 12.1 kB

### CODE REVIEW

**Comment by wemeetagain** [comment]
Not necessarily very useful, PR open more for discussion

**Comment by mpetrunic** [comment]
Doesn't that mean that other wasm projects cannot use this as a library?

**Comment by GregTheGreek** [comment]
what are the different contents within lib/build?

**Comment by GregTheGreek** [comment]
Doesn't lib technically include the build?

**Comment by mpetrunic** [comment]
> Doesn't lib technically include the build?

wasm is inlined in lib. Seems to me that to use this as a lib in other assemblyscript projects, you just need to include assembly directory. not 100% though

**Comment by dapplion** [comment]
Why does it matter to reduce the unpacked package size?

**Comment by wemeetagain** [comment]
> Why does it matter to reduce the unpacked package size?

Good question, when I opened the PR, I'd confused the package size with the bundle size. (and my second comment after realizing unpacked package size isn't very helpful metric :roll_eyes: )

I was originally thinking we could remove the wasm binary, include it in a separate package with the assemblyscript files.
But maybe we should be going the other way, instead of removing the wasm, just also including the files in `assembly/`.

**Comment by mpetrunic** [comment]
From what i saw in other as libraries I think we can exclude wasm but must include assembly. That said they also set types to be assembly/index.ts which will conflict with our type definition

**Comment by wemeetagain** [comment]
Closing this.

A future PR could more fully tackle exposing the assemblyscript functions as a library.

**Pull request closed without merging**
